---
- name: Deploy Tasks
  hosts: localhost
  tags:
    - deploy
  tasks:
    - name: Install packages
      package: 
        name: "{{ item }}"
        state: present
      with_items:
        - httpd
        - php
        - php-mysql
        - php-gd

- name: Configure Tasks
  hosts: localhost
  tags: 
    - configure
  tasks:
    - name: Deploy wordpress files
      copy:
        src: wordpress/
        dest: /var/www/html/