---
- name: Deploy Tasks
  hosts: localhost
  tags:
    - deploy
  tasks:
    - name: Install mysql
      package: 
        name: "{{ item }}"
        state: present
      with_items:
        - mysql-server
        - MySQL-python


