---
- name: Deploy Tasks
  hosts: localhost
  tags:
    - deploy
  tasks:
    - name: Install mysql
      package: 
        name: "{{ item }}"
        state: present
      with_items:
        - mysql-server
        - MySQL-python
    - name: Disable firewalld
      service:
        name: firewalld
        state: stopped
        enabled: no
    - name: Enable and start mysql
      service:
        name: mysqld
        state: started
        enabled: yes


- name: Configure Tasks
  hosts: localhost
  tags: 
    - configure
  tasks:
    - name: Copy database dump
      copy:
        src: wordpress.sql
        dest: /tmp
    - name: Import database
      mysql_db:
        name: "{{ DB_NAME }}"
        state: import
        target: /tmp/wordpress.sql
    - name: Create database user
      mysql_user:
        name: "{{ DB_USER }}"
        password: "{{ DB_PASSWORD }}"
        login_user: root
        priv: "{{ DB_NAME }}.*:ALL"