---
- name: Deploy Tasks
  hosts: localhost
  tags:
    - deploy
  tasks:
    - name: Install nginx (load balancer / reverse proxy)
      package: 
        name: nginx
        state: present
    - name: Disable firewalld
      service:
        name: firewalld
        state: stopped
        enabled: no
    - name: Enable and start nginx
      service:
        name: nginx
        state: started
        enabled: yes

- name: Configure Tasks
  hosts: localhost
  tags: 
    - configure
  tasks:
    - name: Setup nginx configuration
      template:
        src: nginx-default-site.j2
        dest: /etc/nginx/nginx.conf
    - name: Reload nginx configuration
      service:
        name: nginx
        state: reloaded
