---
- name: Deploy Tasks
  hosts: localhost
  tags:
    - deploy
  tasks:
    - name: Install nginx (load balancer / reverse proxy)
      package: 
        name: nginx
        state: present

- name: Configure Tasks
  hosts: localhost
  tags: 
    - configure
  tasks:
    - name: Setup nginx configuration
      template:
        src: nginx-default-site.j2
        dest: /etc/nginx/sites-available/default
    - name: Reload nginx configuration
      service:
        name: nginx
        state: reloaded