---
- name: Deploy Tasks
  hosts: localhost
  tags:
    - deploy
  tasks:
    - name: Install packages
      package: 
        name: "{{ item }}"
        state: present
      with_items:
        - nginx
        - libselinux-python
    - name: Disable firewalld
      service:
        name: firewalld
        state: stopped
        enabled: no
      ignore_errors: yes
    - name: Enable and start nginx
      service:
        name: nginx
        state: started
        enabled: yes

- name: Configure Tasks
  hosts: localhost
  tags: 
    - configure
  tasks:
    - name: Setup nginx configuration
      template:
        src: nginx-default-site.j2
        dest: /etc/nginx/nginx.conf
    - name: Reload nginx configuration
      service:
        name: nginx
        state: reloaded
